module Arm(
	Clk,
	Rst_n,
	in_id,
	Baud_Set_in,
	uart_tx,
	Tx_Done,
	uart_state,
	in_cmd,
	ARM_EN);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input [7:0] in_id;
	input [2:0] Baud_Set_in;
	output uart_tx;
	output Tx_Done;
	output uart_state;
	input in_cmd;
	input ARM_EN;

	wire Clk;
	wire Rst_n;
	wire [7:0] in_id;
	wire [2:0] Baud_Set_in;
	wire uart_tx;
	wire Tx_Done;
	wire uart_state;
	wire in_cmd;
	wire ARM_EN;
	wire [79:0] arm_cal_m2_data_out;
	wire arm_cal_m2_send_en_out;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	uart_data_tx uart_data_tx2(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.data(arm_cal_m2_data_out),
		.send_en(arm_cal_m2_send_en_out),
		.Baud_Set(Baud_Set_in),
		.uart_tx(uart_tx),
		.Tx_Done(Tx_Done),
		.uart_state(uart_state),
		.ARM_EN(ARM_EN));

	arm_cal_m arm_cal_m2(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.input_cmd(in_cmd),
		.data_out(arm_cal_m2_data_out),
		.send_en_out(arm_cal_m2_send_en_out),
		.input_id(in_id));

endmodule    //Arm

