module LM75A_drive(
	Clk,
	Rst_n,
	LM75A_EN,
	Temp_data,
	Read_temp_en,
	SCL,
	SDA);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input LM75A_EN;
	output [10:0] Temp_data;
	output Read_temp_en;
	output SCL;
	inout SDA;

	wire Clk;
	wire Rst_n;
	wire LM75A_EN;
	wire [10:0] Temp_data;
	wire Read_temp_en;
	wire SCL;
	wire SDA;
	wire Read_clock_of_LM75A1_Finish;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	Read_clock_of_LM75A Read_clock_of_LM75A1(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.LM75A_EN(LM75A_EN),
		.Finish(Read_clock_of_LM75A1_Finish));

	LM75A_i2c_control LM75A_i2c_control2(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.rdreg_req(Read_clock_of_LM75A1_Finish),
		.rddata(Temp_data),
		.RW_Done(Read_temp_en),
		.ack( ),
		.i2c_sclk(SCL),
		.i2c_sdat(SDA));

endmodule    //LM75A_drive

