module pwm_generator(
	Clk,
	Rst_n,
	pwm_gen_en,
	counter_arr,
	counter_ccr,
	pwm_out);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input pwm_gen_en;
	input [31:0] counter_arr;
	input [31:0] counter_ccr;
	output pwm_out;

	wire Clk;
	wire Rst_n;
	wire pwm_gen_en;
	wire [31:0] counter_arr;
	wire [31:0] counter_ccr;
	reg pwm_out;

	//----Code starts here: integrated by Robei-----
	
		
		
			reg [31:0]pwm_gen_cnt;   //定义32位产生pwm的计数器
		
			always@(posedge Clk or posedge Rst_n)
			if(!Rst_n )
				pwm_gen_cnt <= 32'd1;
			else if(pwm_gen_en)
			begin
				if(pwm_gen_cnt <= 32'd1)
					pwm_gen_cnt <= counter_arr;       //计数减到1，加载预重装寄存器值
				else
					pwm_gen_cnt <= pwm_gen_cnt - 1'b1;//计数器自减1
			end
			else
				pwm_gen_cnt <= counter_arr;	        //未使能时，计数器值等于预重装寄存器值
		
			always@(posedge Clk or posedge Rst_n)
			if(!Rst_n )                          //复位时，PWM输出低电平
				pwm_out <= 1'b0;
			else if(pwm_gen_cnt <= counter_ccr)   //计数值小于比较值，PWM输出高电平
				pwm_out <= 1'b1;
			else
				pwm_out <= 1'b0;                    //计数值大于比较值，PWM输出低电平
endmodule    //pwm_generator

