module Top(
	Clk,
	Rst_n,
	i_echo,
	uart_rx,
	LCD_CLK,
	MOSI,
	LCD_RES,
	LCD_DC,
	LCD_BLK,
	arm_uart_tx,
	Beeeee,
	MOTOR__sclk,
	MOTOR_sdat,
	o_trig,
	LM75A_SCL,
	LM75A_SDA,
	ARM_TX_EN);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input i_echo;
	input uart_rx;
	output LCD_CLK;
	output MOSI;
	output LCD_RES;
	output LCD_DC;
	output LCD_BLK;
	output arm_uart_tx;
	output Beeeee;
	output MOTOR__sclk;
	inout MOTOR_sdat;
	output o_trig;
	output LM75A_SCL;
	inout LM75A_SDA;
	output ARM_TX_EN;

	wire Clk;
	wire Rst_n;
	wire i_echo;
	wire uart_rx;
	wire LCD_CLK;
	wire MOSI;
	wire LCD_RES;
	wire LCD_DC;
	wire LCD_BLK;
	wire arm_uart_tx;
	wire Beeeee;
	wire MOTOR__sclk;
	wire MOTOR_sdat;
	wire o_trig;
	wire LM75A_SCL;
	wire LM75A_SDA;
	wire ARM_TX_EN;
	wire LM75A_drive5_Read_temp_en;
	wire [10:0] LM75A_drive5_Temp_data;
	wire [15:0] CSB_drive6_data;
	wire Core_of_top6_LM75A_EN;
	wire Core_of_top6_BUZZER_EN;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	Top_Arm_Motor Top_Arm_Motor3(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.uart_rx(uart_rx),
		.arm_uart_tx(arm_uart_tx),
		.motor_i2c_sclk(MOTOR__sclk),
		.motor_i2c_sdat(MOTOR_sdat),
		.arm_en_out(ARM_TX_EN));

	buzzer_drive buzzer_drive4(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.Beeee(Beeeee),
		.BUZZER_EN(Core_of_top6_BUZZER_EN));

	LM75A_drive LM75A_drive5(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.LM75A_EN(Core_of_top6_LM75A_EN),
		.Temp_data(LM75A_drive5_Temp_data),
		.Read_temp_en(LM75A_drive5_Read_temp_en),
		.SCL(LM75A_SCL),
		.SDA(LM75A_SDA));

	CSB_drive CSB_drive6(
		.clk(Clk),
		.rst_n(Rst_n),
		.Echo(i_echo),
		.trig(o_trig),
		.data(CSB_drive6_data));

	TFT_top TFT_top6(
		.clk(Clk),
		.rstn(Rst_n),
		.CLK(LCD_CLK),
		.MOSI(MOSI),
		.RES(LCD_RES),
		.DC(LCD_DC),
		.BLK(LCD_BLK));

	Core_of_top Core_of_top6(
		.Read_temp_ok(LM75A_drive5_Read_temp_en),
		.Temp_data(LM75A_drive5_Temp_data),
		.CSB_data(CSB_drive6_data),
		.LM75A_EN(Core_of_top6_LM75A_EN),
		.BUZZER_EN(Core_of_top6_BUZZER_EN),
		.Clk(Clk),
		.Rst_n(Rst_n));

endmodule    //Top

