# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/TOP.cache/wt [current_project]
set_property parent.project_path E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/TOP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/TOP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/APD_drive.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/APD_i2c_bit_shifter.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/APD_i2c_control.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Arm.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Bus_arm_motor.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Core_of_top.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/LM75A_drive.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/LM75A_i2c_bit_shifter.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/LM75A_i2c_control.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Read_clock_of_APD.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Read_clock_of_LM75A.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Sense_top.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/TFT_driver.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/TFT_top.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Top_Arm_Motor.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Wheel_Instruction_Analysis.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/arm_cal_m.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/arm_en_module.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/i2c_bit_shifter.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/i2c_control_motor_plus.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/single_ROM2.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/sonic.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/sonic_digital.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/uart_byte_rx.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/uart_byte_tx.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/uart_data_tx.v
  E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Top_const.xdc
set_property used_in_implementation false [get_files E:/CodeFile/JueSai/CICC1054/Vivado_prj/TOP/SRC/Top_const.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
