module APD_drive(
	Clk,
	Rst_n,
	APD_EN,
	color,
	Read_color_ok,
	APD_SCL,
	APD_SDA);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input APD_EN;
	output [7:0] color;
	output Read_color_ok;
	output APD_SCL;
	inout APD_SDA;

	wire Clk;
	wire Rst_n;
	wire APD_EN;
	wire [7:0] color;
	wire Read_color_ok;
	wire APD_SCL;
	wire APD_SDA;
	wire Read_clock_of_APD3_Finish;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	Read_clock_of_APD Read_clock_of_APD3(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.APD_EN(APD_EN),
		.Finish(Read_clock_of_APD3_Finish));

	APD_i2c_control APD_i2c_control3(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.rdreg_req(Read_clock_of_APD3_Finish),
		.rddata( ),
		.RW_Done(Read_color_ok),
		.ack( ),
		.i2c_sclk(APD_SCL),
		.i2c_sdat(APD_SDA),
		.COLOR(color));

endmodule    //APD_drive

