module arm_en_module(
	Clk,
	Rst_n,
	 input_flag,
	Tx_flag,
	arm_en);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input [7:0]  input_flag;
	input Tx_flag;
	output arm_en;

	wire Clk;
	wire Rst_n;
	wire [7:0]  input_flag;
	wire Tx_flag;
	reg arm_en;

	//----Code starts here: integrated by Robei-----
	   reg [1:0] switch;
	    reg [2:0] length;
	    always@(posedge Clk or negedge Rst_n)
	    begin
	        if (!Rst_n)
	        begin
	            arm_en <= 1'b0;
	            switch <= 1'b0;
	        end
	        else
	            case (switch)
	            1'b0:
	                begin
	                    if(input_flag != 8'h0)
	                        begin
	                            switch <= 1'b1;
	                            arm_en <= 1'b1;
	                            length <= 3'd1;
	                            if (input_flag >= 8'h7)
	                                length <= length + 3'd6;
	                        end
	                end
	            1'b1:
	                begin
	                    if(Tx_flag == 1'b1)
	                        begin
	                        length = length - 3'd1;
	                        if (length ==3'd0)
	                            begin
	                            switch <= 1'b0;
	                            arm_en <= 1'b0;
	                            end
	                        end
	                end
	            default:
	                begin
	                    switch <= 1'b0;
	                    arm_en <= 1'b0;
	                end
	            endcase
	    end
endmodule    //arm_en_module

