module single_ROM2(
	clk,
	addr,
	q);

	//---Ports declearation: generated by Robei---
	input clk;
	input [18:0] addr;
	output [7:0] q;

	wire clk;
	wire [18:0] addr;
	reg [7:0] q;

	//----Code starts here: integrated by Robei-----
			parameter DATA_WIDTH = 8;
			parameter ADDR_DEPTH = 500000;
			
			    parameter   DELAY   = 1     ;//read data output delay
			
			reg [DATA_WIDTH-1:0] rom[ADDR_DEPTH-1:0];			//			2**ADDR_WIDTH=2^(ADDR_WIDTH)
			
			initial 
			begin
			    $readmemh("E:/CodeFile/JueSai/CICC1054/Vivado_prj/Picture_Data/LCDoutput.txt", rom);   //读取16进制数据
																								//读取2进制数据
			end
			
			reg [DATA_WIDTH-1:0] buffer [0:DELAY];
			
			always @(posedge clk)
			    begin
			
			 //读操作条件，当RDEnable为1且CS为1时，将Addr指定的内存单元中的数据读出并暂存在Data_read中
			   q <= rom[addr];
			 //其他条件，当CS为0或RDEnable为不确定值时，将Data_read置为高阻抗状态
			    end
			
			
			always@(posedge clk) begin
			
			        buffer[1] <= buffer[0];
			
			end
			
			//assign q = buffer[0];
endmodule    //single_ROM2

