module TFT_top(
	clk,
	rstn,
	CLK,
	MOSI,
	RES,
	DC,
	BLK,
	CS);

	//---Ports declearation: generated by Robei---
	input clk;
	input rstn;
	output CLK;
	output MOSI;
	output RES;
	output DC;
	output BLK;
	output CS;

	wire clk;
	wire rstn;
	wire CLK;
	wire MOSI;
	wire RES;
	wire DC;
	wire BLK;
	wire CS;
	wire [18:0] TFT_driver3_addr;
	wire TFT_driver3_clka;
	wire [7:0] single_ROM22_q;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	TFT_driver TFT_driver3(
		.clk(clk),
		.rstn(rstn),
		.pic_data(single_ROM22_q),
		.CLK(CLK),
		.MOSI(MOSI),
		.RES(RES),
		.DC(DC),
		.addr(TFT_driver3_addr),
		.clka(TFT_driver3_clka),
		.ena( ),
		.BLK(BLK),
		.CS(CS));

	single_ROM2 single_ROM22(
		.clk(TFT_driver3_clka),
		.addr(TFT_driver3_addr),
		.q(single_ROM22_q));

endmodule    //TFT_top

