module Top(
	Clk,
	Rst_n,
	i_echo0,
	uart_rx,
	LCD_CLK,
	MOSI,
	LCD_RES,
	LCD_DC,
	LCD_BLK,
	arm_uart_tx,
	Beeeee,
	MOTOR__sclk,
	MOTOR_sdat,
	o_trig0,
	LM_SCL,
	LM_SDA,
	ARM_TX_EN,
	APD_SCL,
	APD_SDA,
	sel,
	LED,
	i_echo1,
	o_trig1,
	CS);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input i_echo0;
	input uart_rx;
	output LCD_CLK;
	output MOSI;
	output LCD_RES;
	output LCD_DC;
	output LCD_BLK;
	output arm_uart_tx;
	output Beeeee;
	output MOTOR__sclk;
	inout MOTOR_sdat;
	output o_trig0;
	output LM_SCL;
	inout LM_SDA;
	output ARM_TX_EN;
	output APD_SCL;
	inout APD_SDA;
	output [3:0] sel;
	output [7:0] LED;
	input i_echo1;
	output o_trig1;
	output CS;

	wire Clk;
	wire Rst_n;
	wire i_echo0;
	wire uart_rx;
	wire LCD_CLK;
	wire MOSI;
	wire LCD_RES;
	wire LCD_DC;
	wire LCD_BLK;
	wire arm_uart_tx;
	wire Beeeee;
	wire MOTOR__sclk;
	wire MOTOR_sdat;
	wire o_trig0;
	wire LM_SCL;
	wire LM_SDA;
	wire ARM_TX_EN;
	wire APD_SCL;
	wire APD_SDA;
	wire [3:0] sel;
	wire [7:0] LED;
	wire i_echo1;
	wire o_trig1;
	wire CS;

	//----Code starts here: integrated by Robei-----
	
	    wire BEEP1;
	    wire BEEP2;
	    assign Beeeee = BEEP1||BEEP2;
	
	
	//---Module instantiation---
	Top_Arm_Motor Top_Arm_Motor3(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.uart_rx(uart_rx),
		.arm_uart_tx(arm_uart_tx),
		.motor_i2c_sclk(MOTOR__sclk),
		.motor_i2c_sdat(MOTOR_sdat),
		.arm_en_out(ARM_TX_EN));

	TFT_top TFT_top6(
		.clk(Clk),
		.rstn(Rst_n),
		.CLK(LCD_CLK),
		.MOSI(MOSI),
		.RES(LCD_RES),
		.DC(LCD_DC),
		.BLK(LCD_BLK),
		.CS(CS));

	Core_of_top Core_of_top6(
		.LM75A_EN( ),
		.Clk(Clk),
		.Rst_n(Rst_n),
		.APD_EN( ));

	Sense_top Sense_top6(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.sel(sel),
		.LED(LED),
		.APD_SCL(APD_SCL),
		.LM_SCL(LM_SCL),
		.APD_SDA(APD_SDA),
		.LM_SDA(LM_SDA));

	sonic sonic5(
		.sys_clk(Clk),
		.rst_n(Rst_n),
		.Echo(i_echo0),
		.trig(o_trig0),
		.BEEP(BEEP1));

	sonic sonic6(
		.sys_clk(Clk),
		.rst_n(Rst_n),
		.Echo(i_echo1),
		.trig(o_trig1),
		.BEEP(BEEP2));

endmodule    //Top

