module Core_of_top(
	LM75A_EN,
	APD_EN,
	Clk,
	Rst_n);

	//---Ports declearation: generated by Robei---
	output LM75A_EN;
	output APD_EN;
	input Clk;
	input Rst_n;

	reg LM75A_EN;
	reg APD_EN;
	wire Clk;
	wire Rst_n;

	//----Code starts here: integrated by Robei-----
					localparam  Min_distance   = 14'd50;   //±¨¾¯¾àÀë
		
		
					reg [10:0] Temp_data_buffer;
					reg [15:0] CSB_data_buffer;
		
		
					always@(posedge Clk or negedge Rst_n)
					if(!Rst_n)begin
						LM75A_EN <= 0;
						APD_EN <=0 ;
		
					end
		
					else begin
						LM75A_EN <= 1;
						APD_EN <=1 ;
		/*
						LCD_EN <= 1;
						ARM_MOTOR_EN <= 1;
						CSB_EN<= 1;
		*/
		
					end
		
		
		
		
					
		
endmodule    //Core_of_top

