module Read_clock_of_LM75A(
	Clk,
	Rst_n,
	LM75A_EN,
	Finish);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	input LM75A_EN;
	output Finish;

	wire Clk;
	wire Rst_n;
	wire LM75A_EN;
	reg Finish;

	//----Code starts here: integrated by Robei-----
			parameter DELAY=33_333_333;
			//parameter DELAY=50; //for test
			    
			    reg [31:0] cnt_delay;
			    reg rst_flag;
			    
			    always@ (posedge Clk or negedge Rst_n)begin
			        if(!Rst_n)begin
			            cnt_delay<=24'b0;
			            Finish<=0;
			        end
			        else if(LM75A_EN)begin
			            if(cnt_delay==DELAY)begin
			               Finish<=1'b1; 
			               cnt_delay<=24'b0;
			            end
			            else begin
			                Finish<=1'b0;
			                cnt_delay<=cnt_delay+1;
			            end                
			         end
			         else begin
			             Finish<=1'b0;
			             cnt_delay<=24'b0;
			         end
			           
			    end
endmodule    //Read_clock_of_LM75A

