module Sense_top(
	Clk,
	Rst_n,
	sel,
	LED,
	APD_SCL,
	LM_SCL,
	APD_SDA,
	LM_SDA);

	//---Ports declearation: generated by Robei---
	input Clk;
	input Rst_n;
	output [3:0] sel;
	output [7:0] LED;
	output APD_SCL;
	output LM_SCL;
	inout APD_SDA;
	inout LM_SDA;

	wire Clk;
	wire Rst_n;
	wire [3:0] sel;
	wire [7:0] LED;
	wire APD_SCL;
	wire LM_SCL;
	wire APD_SDA;
	wire LM_SDA;
	wire [7:0] APD_drive1_color;
	wire [7:0] LM75A_drive2_Temp_data;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	APD_drive APD_drive1(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.APD_EN(1'b1),
		.color(APD_drive1_color),
		.Read_color_ok( ),
		.APD_SCL(APD_SCL),
		.APD_SDA(APD_SDA));

	LM75A_drive LM75A_drive2(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.LM75A_EN(1'b1),
		.Temp_data(LM75A_drive2_Temp_data),
		.Read_temp_en( ),
		.LM_SCL(LM_SCL),
		.LM_SDA(LM_SDA));

	sonic_digital sonic_digital3(
		.Clk(Clk),
		.Rst_n(Rst_n),
		.temp_data(LM75A_drive2_Temp_data),
		.color_data(APD_drive1_color),
		.sel(sel),
		.led_data(LED));

endmodule    //Sense_top

